package bouldercow.flow.effects;

public enum ResourceUnits {
    meat,
    milk,
    wool,
    rye,
    clay,
    leather,
    flax,
    barley,
    hops,
    sheep,
    sheepMovement,
    vp,
    jewelry,
    boulder,
    worker,
    cock,
    tool,
    fieldAnyLvl,//for requirements
    fieldLvl2,
    fieldLvl3,
    fieldLvl4,
    fieldLvl5,
    fieldLvl5WithCrop,
    //other resource in set reps required crop on field since no card requires separate resources and fields
    fieldWithCrop,
    fieldWithoutCrop,
    sowAnyAction,
    //other resource in set reps required crop
    sowSpecificAction,
    gatewayCard,
    farmyardCard,
    bonusCard,
    pointCard,
    //refers to advancing a building.
    building,
    //refers to how many workers are gained each round
    workerSupply,
    actionSpaceFullyOccupied,
    differentCrops,
    harvestAction,
    fieldUpgrade,
    sheepMovementDifferent,
    farmyardCardsPlayed,
    harvestTotal,
    sheepOnSameFarmyard,
    sheepOnFarmyard,
    removeWorkersAction,
    allCrops,
    anyGoods,
    nextTurnSheepCard,
    anyCrops,
    actionSpace, anyCard, hand, emptyFarmyardCards, cardsPlayed, nursery, roundNumber, quadrant, craftBuilding;
}
